config/routes.rb
Rails.application.routes.draw do
  resources :tracked_site_product_indices do
    member do
      get :import_products
    end
  end

  devise_for :users
  
  resources :tracked_sites do
    member do
      get :scrape_latest
      post :add_child_variant
    end
  end
  
  resources :stations do
    member do 
      get :retrieve_hourly_forecast
    end
    collection do 
      get :from_lat_lon_form
      post :create_from_lat_lon 
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :forecasts
  root "stations#index"
end

app/models/station.rb
# == Schema Information
#
# Table name: stations
#
#  id                  :bigint           not null, primary key
#  name                :string(255)
#  code                :string(255)
#  city                :string(255)
#  state               :string(255)
#  data                :text(4294967295)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  last_forecast_time  :datetime
#  current_forecast_id :bigint
#

require 'json'
require 'rest-client'

class Station < ApplicationRecord
  include ::JsonService

  has_many :forecasts, dependent: :destroy
  has_many :predictions, dependent: :destroy
  belongs_to :current_forecast, class_name: "Forecast", foreign_key: "current_forecast_id", optional: true

  serialize :data, JSON

  # returns a hash of state abbreviations => largest temp_diff range for that state
  def self.build_state_range_diffs
    state_diffs = Hash.new(0)
    Station.find_each do |s|
      diff = s.current_forecast&.temp_diff
      state_diffs[s.state] = diff if diff && diff >= state_diffs[s.state]
    end
    state_diffs
  end

  # experimental - work in progress...
  # TODO: how to really represent 
  def self.build_state_errors(strategy = :variance)
    state_diffs = Hash.new(0)
    key = strategy == :variance ? :error_variance : :error_deviation
    Station.find_each do |s|
      f = s.current_forecast
      next if f.nil?
      error = f.current_statistics[key]
      state_diffs[s.state] = error if error && error >= state_diffs[s.state]
    end
    state_diffs
  end

  def self.build_state_days_diff(days_b4 = nil)
      state_diffs = Hash.new(0)
      Station.find_each do |s|
          f = s.current_forecast
          next if f.nil?
          preds = f.predictions_for
          temp_predicted = if days_b4.nil?
              preds[0].temperature
          else
              raise "todo"
              preds.detect{|p| p.created_at}
          end
          diff = f.current_temp - temp_predicted
          state_diffs[s.state] = diff if diff && diff.abs >= state_diffs[s.state].abs
      end
      state_diffs
  end

  def properties
    data['properties']
  end

  def time_zone
    properties['timeZone']
  end

  def start_and_end_utc_times_for_date(date)
    b4 = Time.zone
    Time.zone = self.time_zone
    if date.is_a?(String)
      date = Date.parse(date)
    end
    date = date.in_time_zone(Time.zone)
    dates = [date.beginning_of_day.utc, date.end_of_day.utc]
    puts "Start and end utc times for '#{date}'[#{Time.zone}] -- #{dates}"
    dates
  ensure
    Time.zone = b4
  end

  def day_summary(date)
    dates = start_and_end_utc_times_for_date(date)
    preds = self.predictions.where("start_time >= ? and start_time <= ?", *dates)
    grouped = preds.group_by{|p| p.start_time}
    Hash[grouped.map do |start_time, preds|
      [
        start_time.in_time_zone(self.time_zone).strftime("%I%P"), 
        Prediction.summarize_for_start_time(preds)
      ]
    end]
  end

  def current_temp
    current_forecast.current_prediction.temperature 
  rescue => e 
    "N/A"
  end

  def current_wind
    current_forecast.current_prediction.wind_speed
  rescue => e 
    "N/A"
  end



  # def __current_forecast
  #   forecasts.order("time DESC").first
  # end

  def compute_largest_diffs(top_n = 10)
    self.forecasts.order("temp_diff DESC").limit(10).map do |f|
      f.attributes.except('id', 'updated_at', 'created_at')
     end
  end

  def self.compute_largest_diffs
    largest_diffs = Station.find_each.map{|s| s.compute_largest_diffs(1)[0].merge({'station_id' => s.id, 
                                                                                'station_name' => s.name, 
                                                                                'station_state' => s.state })}
    largest_diffs.sort{|a,b| b['temp_diff'] <=> a['temp_diff']}
  end

  def self.retrieve_new_forecasts
    Station.find_each do |s| 
      begin
        if s.current_forecast.time > 1.hour.ago
          puts "Skipping Station[#{s.code}]"
          next
        end
        s.get_hourly_forecast
      rescue => e
        Rails.logger.error "Error retrieving new forecasts: #{e.message}"
        Rails.logger.error e.backtrace.join("\n")
      end
      sleep(5)
    end
  end

  def get_hourly_forecast
    Rails.logger.info "Station[#{code}].get_hourly_forecast"
    url = properties["forecastHourly"]
    data = json_service(url)   
    if data.nil?
      puts "No data returned - using current forecast"
      return current_forecast
    end
    _predictions = data['properties']['periods']
    # use the first startTime for recording all predictions
    forecast_time = Time.parse _predictions[0]['startTime']
    forecast = forecasts.where(time: forecast_time).first_or_create
    # Return if we've already processed these predictions
    if forecast.predictions.count > 0
      Rails.logger.info "  Forecast[#{forecast.id}] already had predictions for time: #{forecast_time}"
      return forecast
    end
    ActiveRecord::Base.transaction do
      _predictions.map do |p|
        start_time = Time.parse p['startTime']
        end_time = Time.parse p['endTime']
        temperature = p['temperature']
        temperature_unit = p['temperatureUnit']
        wind_speed, wind_unit = p['windSpeed'].split(" ") rescue [nil, nil]
        wind_direction = p['windDirection']
        short_forecast = p['shortForecast']
        if temperature.nil?
          raise "Invalid temperature encountered in prediction for Station[#{self.id}]" 
        end
        # icon eg: "https://api.weather.gov/icons/land/night/bkn?size=small"
        icon = p['icon'].split("/").last.split("?").first.gsub(",", "_") rescue nil

        forecast.predictions.create(station: self,
                                  start_time: start_time,
                                    end_time: end_time,
                                    temperature: temperature,
                                    temperature_unit: temperature_unit,
                                    wind_speed: wind_speed,
                                    wind_unit: wind_unit,
                                    wind_direction: wind_direction,
                                    short_forecast: short_forecast,
                                    icon: icon)
      end
      forecast.send(:compute_stats)
      forecast.end_time = forecast.predictions.last.start_time
      forecast.save!
      self.last_forecast_time = forecast_time
      self.current_forecast = forecast
      self.save!
    end # ActiveRecord::Base.transaction do
    return forecast
  end

  def self.create_from_lat_lon(lat, lon)
    station = Station.new
    url = "https://api.weather.gov/points/#{lat},#{lon}"
    data = station.json_service(url)
    station.data = data.as_json 
    station.code = data['properties']['cwa']
    station.name = data['properties']['relativeLocation']['properties']['city']
    station.city = data['properties']['relativeLocation']['properties']['city']
    station.state = data['properties']['relativeLocation']['properties']['state']
    station.save!
    return station
  end

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update,
                :destroy, :retrieve_hourly_forecast]

  def from_lat_lon_form
  end 

  def create_from_lat_lon
    lat = params[:coords][:lat]
    lon = params[:coords][:lon]
    s = Station.create_from_lat_lon(lat, lon)
    redirect_to s, notice: "Station created from lat:#{lat} lon:#{lon}"
  end

  def retrieve_hourly_forecast
    @forecast = @station.get_hourly_forecast
    redirect_to @forecast
  end

  # GET /stations
  # GET /stations.json
  def index
    params[:chart_type] ||= 'reality_check'
    @q = Station.ransack(params[:q])
    @q.sorts = 'current_forecast_temp_diff DESC' if @q.sorts.blank?    
    @stations = @q.result
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :code, :city, :state, :data)
    end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.haml
= form_for @station, html: { class: "form-horizontal", role: "form" } do |f|
  -if @station.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@station.errors.count, "error")} prohibited this station from being saved:"

      %ul
        - @station.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :code, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :code, class: 'form-control'
  .form-group
    = f.label :city, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :city, class: 'form-control'
  .form-group
    = f.label :state, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :state, class: 'form-control'
  .form-group
    = f.label :data, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :data, class: 'form-control', rows: 10
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/stations/edit.html.haml
.page-header
  .float-right
    = link_to stations_path, class: 'btn btn-info' do
      %span.glyphicon.glyphicon-list-alt
      Back
    = link_to @station, class: 'btn btn-primary' do
      %span.glyphicon.glyphicon-info-sign
      Show
    = link_to 'Destroy', @station, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

  %h1 Editing station

= render 'form'

app/views/stations/from_lat_lon_form.html.haml
%h1 
  Create Forecast Location
  %small
    From lat/lon

=form_for :coords, url: create_from_lat_lon_stations_path do |f|
  =f.text_field :lat, placeholder: "lat" 
  =f.text_field :lon, placeholder: "lon"
  =f.submit "Create from lat lon"

app/views/stations/index.html.haml
-color_axis = "['white', 'red']"
-label = 'Error'
-if params[:chart_type] == 'error_deviation'
  -state_diffs = Station.build_state_errors(:deviation)
-elsif params[:chart_type] == 'error_variance'
  -state_diffs = Station.build_state_errors(:variance)
-elsif params[:chart_type] == 'reality_check'
  -state_diffs = Station.build_state_days_diff()
  -color_axis = "['blue', 'white', 'red']"
  -label = 'Actual temperature vs original prediction'
  -# To make the range of values balanced and 0-centered
  -min = state_diffs.values.min
  -max = state_diffs.values.max
  -if min.abs > max.abs
    -state_diffs['ZZ'] = min.abs
  -else
    -state_diffs['ZZ'] = -1 * max.abs


-elsif params[:chart_type] == 'diffs'
  -state_diffs = Station.build_state_range_diffs
  -label = "Range of predictions"

-content_for(:head) do
  :plain
    <script type='text/javascript' src='https://www.gstatic.com/charts/loader.js'></script>
    <script type='text/javascript'>
     google.charts.load('current', {
       'packages': ['geochart'],
       // Note: Because markers require geocoding, you'll need a mapsApiKey.
       // See: https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings
       'mapsApiKey': 'AIzaSyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY'
     });
     google.charts.setOnLoadCallback(drawMarkersMap);

      function drawMarkersMap() {
      var data = google.visualization.arrayToDataTable([
        ['State',   '#{label.html_safe}'],
        #{state_diffs.map{|k,v| "['#{k}',#{v}]"}.join(",").html_safe}
      ]);

      var options = {
        width: 556, height: 347,
        min: -15, max: 15,
        region: 'US',
        resolution: 'provinces',
        colorAxis: {colors: #{color_axis.html_safe}, min: -15, max: 15}
      };

      var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
      chart.draw(data, options);
    };
    </script>

.page-header
  .float-right
    = link_to 'New Station', from_lat_lon_form_stations_path, class: "bg-green-700 hover:bg-green-600 px-1 py-0 rounded text-white"
      
  %h1{class: 'text-3xl'} Listing #{@stations.length} Stations

#chart_div

%div{class: "relative overflow-x-auto shadow-md sm:rounded-lg"}
  %table{class: "w-full text-sm text-left text-gray-500 dark:text-gray-400"}
    %thead{class: "text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"}
      %tr{class: "bg-white border-b dark:bg-gray-800 dark:border-gray-700"}
        %th=sort_link(@q, :name)
        %th=sort_link(@q, :code)
        %th=sort_link(@q, :city)
        %th=sort_link(@q, :state)
        / %th Location
        %th Temp
        %th Range
        %th=sort_link(@q, :current_forecast_temp_diff, "Diff")

        %th Wind
        %th Range
        %th=sort_link(@q, :current_forecast_wind_diff, "Diff")

        %th=sort_link(@q, :last_forecast_time, "Last Forecast")

    %tbody
      - @stations.each do |station|
        %tr{class: "bg-white border-b dark:bg-gray-800 dark:border-gray-700"}
          %td= link_to station.name, station
          %td= station.code
          %td= station.city
          %td= station.state
          / %td= station.properties.dig('relativeLocation', 'geometry', 'coordinates')
          %td=station.current_temp
          %td=station.current_forecast&.previous_prediction_range(:temp)
          %td=render "shared/diff_badge", difference: station.current_forecast&.temp_diff

          %td=station.current_wind
          %td=station.current_forecast&.previous_prediction_range(:wind)
          %td=render "shared/diff_badge", difference: station.current_forecast&.wind_diff

          %td= station.current_forecast&.time.try(:strftime, "%m/%d/%Y %H:%M")

app/views/stations/new.html.haml
.page-header
  = link_to stations_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New station

= render 'form'

app/views/stations/show.html.haml
.page-header
  .float-right
    = link_to 'Get Current Forecast', retrieve_hourly_forecast_station_path(@station), class: 'bg-green-500 hover:bg-green-700 text-white px-1 py-0 rounded'
    = link_to 'Back', stations_path, class: 'bg-blue-500 hover:bg-blue-700 px-1 py-0 rounded text-white'
    = link_to 'Edit', edit_station_path(@station), class:"bg-cyan-500 hover:bg-cyan-700 px-1 py-0 rounded text-white"
    = link_to 'Destroy', @station, class: "bg-red-500 hover:bg-red-700 px-1 py-0 rounded text-white", method: :delete, data: { confirm: "Are you sure you want to destroy Station[#{@station.id}] #{@station.city}/#{@station.state}[#{@station.code}]"}

  %h1{class: "text-3xl"}
    = @station.name
    %small
      =@station.code
      %small
        =@station.city
        ,
        =@station.state
  %table.table.table-condensed.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Forecast Time
        %th Temp Diff
        %th Wind Diff
    %tbody
      -@station.forecasts.order("time desc").each do |forecast|
        %tr
          %td=link_to (l forecast.time), forecast
          %td=render "shared/diff_badge", difference: forecast.temp_diff
          %td=render "shared/diff_badge", difference: forecast.wind_diff