config/routes.rb
Rails.application.routes.draw do
  resources :tracked_site_product_indices do
    member do
      get :import_products
    end
  end

  devise_for :users
  
  resources :tracked_sites do
    member do
      get :scrape_latest
      post :add_child_variant
    end
  end
  
  resources :stations do
    member do 
      get :retrieve_hourly_forecast
    end
    collection do 
      get :from_lat_lon_form
      post :create_from_lat_lon 
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :forecasts
  root "stations#index"
end

app/controllers/tracked_site_product_indices_controller.rb
class TrackedSiteProductIndicesController < ApplicationController
  before_action :set_tracked_site_product_index, only: %i[ show edit update destroy import_products ]

  # GET /tracked_site_product_indices or /tracked_site_product_indices.json
  def index
    @tracked_site_product_indices = TrackedSiteProductIndex.all
  end

  # GET /tracked_site_product_indices/1 or /tracked_site_product_indices/1.json
  def show
  end

  def import_products
    stats = @tracked_site_product_index.import_products
    redirect_to @tracked_site_product_index, notice: stats.to_s
  end

  # GET /tracked_site_product_indices/new
  def new
    @tracked_site_product_index = TrackedSiteProductIndex.new
  end

  # GET /tracked_site_product_indices/1/edit
  def edit
  end

  # POST /tracked_site_product_indices or /tracked_site_product_indices.json
  def create
    @tracked_site_product_index = TrackedSiteProductIndex.new(tracked_site_product_index_params)

    respond_to do |format|
      if @tracked_site_product_index.save
        format.html { redirect_to tracked_site_product_index_url(@tracked_site_product_index), notice: "Tracked site product index was successfully created." }
        format.json { render :show, status: :created, location: @tracked_site_product_index }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tracked_site_product_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracked_site_product_indices/1 or /tracked_site_product_indices/1.json
  def update
    respond_to do |format|
      if @tracked_site_product_index.update(tracked_site_product_index_params)
        format.html { redirect_to tracked_site_product_index_url(@tracked_site_product_index), notice: "Tracked site product index was successfully updated." }
        format.json { render :show, status: :ok, location: @tracked_site_product_index }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tracked_site_product_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracked_site_product_indices/1 or /tracked_site_product_indices/1.json
  def destroy
    @tracked_site_product_index.destroy

    respond_to do |format|
      format.html { redirect_to tracked_site_product_indices_url, notice: "Tracked site product index was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracked_site_product_index
      @tracked_site_product_index = TrackedSiteProductIndex.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tracked_site_product_index_params
      params.require(:tracked_site_product_index).permit(:tracked_site_class, :product_index_url, :category, :sub_category)
    end
end

app/helpers/tracked_site_product_indices_helper.rb
module TrackedSiteProductIndicesHelper
end

app/views/tracked_site_product_indices/_form.html.haml
.w-full.max-w-xl.flex.justify-center
  = form_for @tracked_site_product_index, html: { class: "w-full bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", role: "form" } do |f|
    -if @tracked_site_product_index.errors.any?
      .alert.alert-danger.alert-dismissable{role: "alert"}
        %button.close{type: "button", data: {dismiss: "alert"} }
          %span{aria: {hidden: "true"} } &times;
          %span.sr-only Close
        %h4= "#{pluralize(@tracked_site_product_index.errors.count, "error")} prohibited this tracked_site_product_index from being saved:"

        %ul
          - @tracked_site_product_index.errors.full_messages.each do |msg|
            %li= msg

    -%i(tracked_site_class product_index_url category sub_category).each do |field|
      .flex.flex-wrap.-mx-3.mb-6
        .w-full.px-3  
          = f.text_field field, class: 'appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="form_field_#{field}', placeholder: field.to_s.titleize
    .flex.flex-wrap.-mx-3.mb-6
      .w-full.px-3  
        = f.submit class: 'action-primary'

app/views/tracked_site_product_indices/edit.html.haml
.page-header
  = link_to tracked_site_product_indices_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @tracked_site_product_index, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing tracked_site_product_index

= render 'form'

app/views/tracked_site_product_indices/index.html.haml
.page-header
  = link_to new_tracked_site_product_index_path, class: 'float-right action-secondary' do
    %span.glyphicon.glyphicon-plus
    New Tracked site product index
  %h1.text-xl Listing Tracked Site Product Indices

%div{class: "relative overflow-x-auto shadow-md sm:rounded-lg mt-4"}
  %table{class: "w-full text-sm text-left text-gray-500 dark:text-gray-400"}
    %thead{class: "text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"}
      %tr{class: "bg-white border-b dark:bg-gray-800 dark:border-gray-700"}
        %th Tracked Site Class
        %th Product Index Url
        %th Category
        %th Sub Category
        %th Product URLs
        %th Linked Products
        %th
        %th
        %th

    %tbody
      - @tracked_site_product_indices.each do |tracked_site_product_index|
        %tr{class: "bg-white border-b dark:bg-gray-800 dark:border-gray-700"}
          %td= tracked_site_product_index.tracked_site_class
          %td= tracked_site_product_index.product_index_url
          %td
            = link_to tracked_sites_path(category: tracked_site_product_index.category,site_source: tracked_site_product_index.tracked_site_class), class: 'action-back' do
              =tracked_site_product_index.category
          %td= tracked_site_product_index.sub_category
          %td= tracked_site_product_index.data&.dig('product_urls')&.length 
          %td= tracked_site_product_index.tracked_sites.length
          %td= link_to 'Show', tracked_site_product_index
          %td= link_to 'Edit', edit_tracked_site_product_index_path(tracked_site_product_index)
          %td= link_to 'Destroy', tracked_site_product_index, data: { confirm: 'Are you sure?' }, method: :delete, class: "bg-red-500 hover:bg-red-700 px-1 py-0 rounded text-white"

app/views/tracked_site_product_indices/new.html.haml
.page-header
  = link_to tracked_site_product_indices_path, class: 'action-back' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h2.text-xl New tracked_site_product_index

= render 'form'

app/views/tracked_site_product_indices/show.html.haml
.page-header
  = link_to tracked_site_product_indices_path, class: 'action-back' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_tracked_site_path(@tracked_site_product_index), class: 'action-edit' do
    Edit
  = link_to tracked_sites_path(category: @tracked_site_product_index.category,site_source: @tracked_site_product_index.tracked_site_class), class: 'action-secondary' do
    =@tracked_site_product_index.category

  %h2.text-2xl 
    Showing #{@tracked_site_product_index.category} #{@tracked_site_product_index.sub_category} for #{@tracked_site_product_index.tracked_site_class}
    %span.text-xs.text-gray-500
      (#{link_to @tracked_site_product_index.product_index_url, @tracked_site_product_index.product_index_url, target: "_blank"})

=link_to 'Import Products', import_products_tracked_site_product_index_path(@tracked_site_product_index), class: 'action-secondary float-right'

- if @tracked_site_product_index.tracked_sites.length > 0
  .flex.flex-row.justify-between.py-5.mx-10
    .grid.grid-cols-1.gap-8.mx-5{class: "md:grid-cols-4"}
      - @tracked_site_product_index.tracked_sites.each do |tracked_site|
        %div
          = render 'tracked_sites/card', tracked_site: tracked_site

- else
  %div.text-2xl.text-center.alert.alert-info
    No tracked sites found for this index

- if (product_urls = @tracked_site_product_index.data&.dig('product_urls') || []).length > 0
  %div.text-2xl.text-center.alert.alert-info
    #{product_urls.length} product urls found
    %span.text-xs.text-gray-500
      (#{link_to @tracked_site_product_index.product_index_url, @tracked_site_product_index.product_index_url, target: "_blank"})

  .grid.grid-cols-1.gap-8.mx-5{class: "md:grid-cols-4"}
    - product_urls.each do |url|
      %div
        %a{href: url, target: "_blank"}= url
- else
  %div.text-2xl.text-center.alert.alert-info
    No product urls found for this index
    %span.text-xs.text-gray-500
      (#{link_to @tracked_site_product_index.product_index_url, @tracked_site_product_index.product_index_url, target: "_blank"})