config/routes.rb
Rails.application.routes.draw do
  resources :tracked_site_product_indices do
    member do
      get :import_products
    end
  end

  devise_for :users
  
  resources :tracked_sites do
    member do
      get :scrape_latest
      post :add_child_variant
    end
  end
  
  resources :stations do
    member do 
      get :retrieve_hourly_forecast
    end
    collection do 
      get :from_lat_lon_form
      post :create_from_lat_lon 
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :forecasts
  root "stations#index"
end

app/models/tracked_site.rb
# == Schema Information
#
# Table name: tracked_sites
#
#  id                                  :bigint           not null, primary key
#  name                                :string(255)
#  url                                 :string(255)
#  category                            :string(255)
#  sub_category                        :string(255)
#  created_at                          :datetime         not null
#  updated_at                          :datetime         not null
#  type                                :string(64)
#  current_price                       :decimal(10, 2)
#  current_price_date                  :datetime
#  lowest_price                        :decimal(10, 2)
#  lowest_price_date                   :datetime
#  lowest_price_tracked_site_datum_id  :bigint
#  highest_price                       :decimal(10, 2)
#  highest_price_date                  :datetime
#  highest_price_tracked_site_datum_id :bigint
#  unavailable                         :boolean          default(FALSE)
#  tracked_site_parent_id              :bigint
#  variant_definition                  :text(4294967295)
#  tracked_site_product_index_id       :bigint
#

require 'nokogiri'
require 'open-uri'

class TrackedSite < ApplicationRecord

  # child variants
  belongs_to :tracked_site_parent, optional: true, class_name: "TrackedSite"
  serialize :variant_definition, JSON

  # has_many :child_variants, class_name: "TrackedSite", inverse_of: :tracked_site_parent

  has_many :_actual_tracked_site_data, dependent: :destroy, class_name: "TrackedSiteDatum"
  has_one_attached :image

  belongs_to :lowest_price_tracked_site_datum, class_name: "TrackedSiteDatum", optional: true
  belongs_to :highest_price_tracked_site_datum, class_name: "TrackedSiteDatum", optional: true

  belongs_to :tracked_site_product_index, optional: true
  
  after_create :do_initial_scrape
  
  after_commit :raise_pricing_events, on: :update

  # default_scope ->() { where(unavailable: nil) }

  scope :unavailable, ->() { where(unavailable: true) }
  scope :available, ->() { where(unavailable: nil) }

  scope :best_price_ever, ->(){ where("current_price = lowest_price")
                                .where("current_price < highest_price")}



  def is_best_price_ever?
    self.current_price == self.lowest_price && self.current_price < self.highest_price
  end
  
  def self.display_name; "The Name for display on webpage"; end

  def display_name
    if is_child_variant?
      "#{name} - #{variant_definition}"
    elsif get_default_variant.present?
      "#{name} - #{get_default_variant}"
    else
      name
    end
  end

  def log_name; "#{self.class.to_s}[#{self.id}]"; end
  
  def get_pricing_unit; "$"; end
  
  def get_default_variant; nil; end
  def get_pricing_variants; []; end

  def ensure_valid_variant!(variant)
    variant = JSON.parse(variant) if variant.is_a?(String)
    found = get_pricing_variants.detect{|v| v == variant}
    raise "#{variant} is not a valid variant for #{self.class}" if !found
    found
  end


  def get_price_for(tsd, variant=variant_definition)
    tsd.data['price']
  end

  # no explicit link like lowest/highest...
  def current_price_tracked_site_datum
    tracked_site_data.last
  end

  def get_current_price(variant=variant_definition)
    get_price_for(current_price_tracked_site_datum, variant)
  end

  def tracked_site_data
    if is_child_variant?
      # use the parent's data
      tracked_site_parent._actual_tracked_site_data
    else
      _actual_tracked_site_data
    end
  end
  
  def is_child_variant?
    return true if tracked_site_parent_id.present?
  end

  def create_child_variant(variant)
    raise "Cannot nest child variants - call on the parent please" if is_child_variant?
    raise "No pricing variants defined" if get_pricing_variants.blank?
    valid_variant = ensure_valid_variant!(variant)
    # 1 - make sure the variant is valid
    tsd = tracked_site_data.last
    variant_price = tsd.get_price(valid_variant)
    raise "Could not get variant price for #{variant}" if variant_price == -1
    excluded = %w[id url current_price current_price_date 
        lowest_price lowest_price_date lowest_price_tracked_site_datum_id
        highest_price highest_price_date highest_price_tracked_site_datum_id]

    attrs = self.attributes.clone
    child = TrackedSite.new(attrs.except(*excluded))
    child.tracked_site_parent = self
    child.variant_definition = valid_variant
    child.save!
    # set child pricing
    child.tracked_site_data.each{|tsd| child.update_stats(tsd)}
    child
  end

  def child_variants
    TrackedSite.where(tracked_site_parent_id: self.id)
  end

  # build_price_journey returns price changes and dates along with deltas
   # [
   # {:price=>863800, :date=>Sun, 31 Jul 2022, :delta=>-3200},
   # {:price=>859600, :date=>Tue, 02 Aug 2022, :delta=>-4200},
   # {:price=>854800, :date=>Sat, 06 Aug 2022, :delta=>-4800},
   # {:price=>814700, :date=>Sun, 04 Sep 2022, :delta=>-40100},
   # {:price=>810500, :date=>Fri, 09 Sep 2022, :delta=>-4200},
   # {:price=>808000, :date=>Thu, 15 Sep 2022, :delta=>-2500}
   # ]
  def build_price_journey(limit: 30, for_specific_tsd: nil)
    puts "TrackedSite[#{self.id}].build_price_journey(limit: #{limit}, for_specific_tsd: #{for_specific_tsd&.id})"
    items = []
    last_price = nil
    scope = if for_specific_tsd.present?
      # find info for a single tsd - include only the previous tsd and this one
      for_specific_tsd.get_previous(5).to_a.reverse + [for_specific_tsd]
    else
      tracked_site_data.last(limit+10)
    end

    scope.each do |tsd|
      price = tsd.get_price(self.variant_definition)
      if price != last_price
        # puts "#{last_price}  #{price}  #{tsd.start_time}"
        item = { tsd_id: tsd.id, price: price, date: tsd.start_time}
        item[:delta] = price - last_price if last_price
        items << item
      end
      last_price = price
    end
    for_specific_tsd ? [items.last] : items.reverse[0..(limit-1)]
  end

  def raise_pricing_events
    new_val = ->(k) { previous_changes[k][1] rescue nil}
    old_val = ->(k) { previous_changes[k][0] rescue nil}

    new_value_is = ->(attribute_name, operation = ">") do
      v1, v2 = previous_changes[attribute_name]
      if v1 && v2
        v2.send(operation, v1)
      else
        false
      end
    rescue Exception => e
      puts ""
    end
    # previous changes is a hash of arrays as such:
      # ap previous_changes
      # {
      #       "updated_at" => [
      #         [0] Sat, 10 Sep 2022 22:06:43.000000000 UTC +00:00,
      #         [1] Sat, 10 Sep 2022 22:07:10.000000000 UTC +00:00
      #     ],
      #     "lowest_price" => [
      #         [0] 15.0,   # old_value
      #         [1] 0.0     # new_value
      #     ]
      # }    
    # EVENTS - raise them, log them, run rules based on them
    # 
    # SaleStarted
    # SaleFinished
    #
    # CurrentPriceIncreased?
    if new_val.("current_price") && old_val.("current_price")
      ap previous_changes
      if new_val.("current_price") > old_val.("current_price")
        raise_event("CurrentPriceIncreased", self)
        # LowestEverPriceFinished?
        if old_val.("current_price") == self.lowest_price
          raise_event("LowestEverPriceFinished", self)
        end
      end
      # CurrentPriceDecreased?
      if new_val.("current_price") < old_val.("current_price")
        raise_event("CurrentPriceDecreased", self)
      end
      # 
      # LowestEverPriceStarted?
      if new_val.("lowest_price") < old_val.("lowest_price") || new_val.("current_price") == self.lowest_price
        raise_event("LowestEverPriceStarted", self)
      end
    end
  rescue => e
    # Rails.logger.error e.backtrace.join("\n")
    Rails.logger.error "Not raising events for #{self.log_name}: #{e.message}"
  end

  def raise_event(event_name, instance)
    klass = instance.class.to_s
    id = instance.id
    puts "#{event_name} triggered on #{klass}[#{id}]"
  end

  def self.scrape_latest
    b4 = TrackedSiteDatum.count
    skipped, errors = 0, 0
    error_ids = []
    TrackedSite.available.find_each do |ts|
      next if ts.is_child_variant?
      begin
        result = ts.scrape_latest
        skipped += 1 if result.nil?
      rescue => e
        errors += 1
        error_ids << ts.id
      end
    end
    after = TrackedSiteDatum.count
    sites_scraped = TrackedSite.count - skipped
    puts "Updated #{sites_scraped} sites - #{after - b4} had new data - #{errors} errors encountered".yellow
    puts "TrackedSite error ids: #{error_ids}".red
  end

  def get_data_html(tracked_site_datum)
    "#{tracked_site_datum.start_time.strftime("%m/%d/%Y")} : #{tracked_site_datum.data.class}"
  end

  def scrape_latest(force = false)
    if tracked_site_data.blank?
      Rails.logger.warn "Not performing TrackedSite[#{self.id}].scrape_latest as no tracked_site_data have been populated"
      return nil
    end
    data = scrape_html
    track_data(data) if data
    if child_variants.present?
      child_variants.each do |cv|
        cv.update_stats( self.tracked_site_data.last )
      end
    end
    data
  rescue => e
    Rails.logger.error "Error scraping TrackedSite[#{self.id}][#{self.name}] - #{e.message}"
    Rails.logger.error e.backtrace.join("\n")
  end

  # Will scrape the HTML from either the #url or the provided filepath ("aaa_gas_prices.html")
  def scrape_html(filepath=nil)
    if filepath.present?
      doc = Nokogiri::HTML(File.readlines(filepath).join("\n"))
      source_location = filepath
    else
      doc = Nokogiri::HTML(URI.open(self.url, {ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE}))
      source_location = self.url
    end
    puts "Got #{doc.to_s.length} bytes from #{source_location}".light_magenta.on_light_yellow
    doc
  rescue => e
    Rails.logger.error("Error encountered scraping #{source_location}")
    Rails.logger.error(e.backtrace.join("\n"))
    Rails.logger.error("Error encountered scraping #{source_location}")

app/models/tracked_sites/aaa_gas_prices.rb
# == Schema Information
#
# Table name: tracked_sites
#
#  id                                  :bigint           not null, primary key
#  name                                :string(255)
#  url                                 :string(255)
#  category                            :string(255)
#  sub_category                        :string(255)
#  created_at                          :datetime         not null
#  updated_at                          :datetime         not null
#  type                                :string(64)
#  current_price                       :decimal(10, 2)
#  current_price_date                  :datetime
#  lowest_price                        :decimal(10, 2)
#  lowest_price_date                   :datetime
#  lowest_price_tracked_site_datum_id  :bigint
#  highest_price                       :decimal(10, 2)
#  highest_price_date                  :datetime
#  highest_price_tracked_site_datum_id :bigint
#  unavailable                         :boolean          default(FALSE)
#  tracked_site_parent_id              :bigint
#  variant_definition                  :text(4294967295)
#  tracked_site_product_index_id       :bigint
#
module TrackedSites
  class AaaGasPrices < ::TrackedSite

    # To keep controller/view/form helpers from needing attention
    # https://stackoverflow.com/questions/4507149/best-practices-to-handle-routes-for-sti-subclasses-in-rails
    def self.model_name
      TrackedSite.model_name
    end

    def self.display_name; "AAA Gas Prices"; end

    # Returns an array of arrays like:
    #   [["[Premium]Gold Products 1 OZ - US Eagle", "Singles"]]
    def get_pricing_variants
      tracked_site_data.last.data.map do |item|
        [item['state']].product(item.except('state').keys)
      end.flatten(1)
    end

    def get_default_variant; ["Utah", "regular"]; end

    # price should always return a hash with :price and :regular_price keys
    def get_price_for(tsd, variant=nil)
      variant ||= get_default_variant
      price = tsd.data.detect{|row| row["state"] == variant[0]}[variant[1]] rescue -1
      price # {price: price, regular_price: nil}
    end

    def get_data_html(tracked_site_datum)
       utah_price = get_price_for(tracked_site_datum, ["Utah", "regular"])
       tn_price = get_price_for(tracked_site_datum, ["Tennessee", "regular"])
       "#{tracked_site_datum.start_time.strftime("%m/%d/%Y")}: UT $#{utah_price}  TN $#{tn_price}"
    end

    def scrape_html(filepath=nil)
      doc = super(filepath)
      table = doc.css("table.sortable-table")
      data = table.css("tr").map do |r|
        cols = r.css("td")
        next if cols.length < 1
        { 
          state: cols[0].css("a").text.squish, 
          regular: cols[1].text.squish.gsub("$","").to_f, 
          mid_grade: cols[2].text.squish.gsub("$","").to_f, 
          premium: cols[3].text.squish.gsub("$","").to_f, 
          diesel: cols[4].text.squish.gsub("$","").to_f
        }.stringify_keys
      end.compact
      data.sort!{|a,b| a['state'] <=> b['state']}
      data      
    end
    
  end

end

app/controllers/tracked_sites_controller.rb
class TrackedSitesController < ApplicationController
  before_action :set_tracked_site, 
    only: [:show, :edit, :update, :destroy, :scrape_latest, :add_child_variant]

  # GET /tracked_sites
  # GET /tracked_sites.json
  def index
    @classes = TrackedSite.descendants.sort_by{|d| d.display_name}
    @class = TrackedSite.descendants.detect{|d| d.display_name == params[:site_source]}
    show_unavailable = params[:show_unavailable] == 'true'
    scope = show_unavailable ? TrackedSite.unavailable : TrackedSite.available
    if @class.present?
      scope = scope.where(type: @class.to_s)
      @categories = scope.where(type: @class.to_s).group(:category).count
      @title = "#{@class.display_name}"
    else
      @categories = []
    end
    @best_buy_lowest_prices = []
    if params[:category].present?
      scope = scope.where(category: params[:category])
      @title = "#{@title} - #{params[:category]}"
    elsif @class == TrackedSites::BestBuy
      @best_buy_lowest_prices = TrackedSites::BestBuy.joins(:lowest_price_tracked_site_datum).best_price_ever.order("tracked_site_data.start_time DESC")
      scope = []
    elsif show_unavailable
      scope = scope.order(current_price_date: :desc)
    elsif @class.blank?
      # show only the products at their best price ever on general index
      scope = scope.best_price_ever
    end
    @tracked_sites = scope
  end

  # GET /tracked_sites/1
  # GET /tracked_sites/1.json
  def show
  end

  def scrape_latest
    start = Time.now
    @tracked_site.scrape_latest
    redirect_to @tracked_site, notice: "#{@tracked_site.name} scraped in #{(Time.now - start).round(2)} seconds"
  end

  def add_child_variant
    variant = params[:variant]
    child_variant = @tracked_site.create_child_variant(variant)
    redirect_to child_variant, notice: "New variant made from #{@tracked_site.display_name}"
  rescue => e
    redirect_back_or_to tracked_site_path(@tracked_site), notice: "Could not create child variant: #{e.message}"
  end

  # GET /tracked_sites/new
  def new
    @tracked_site = TrackedSite.new
  end

  # GET /tracked_sites/1/edit
  def edit
  end

  # POST /tracked_sites
  # POST /tracked_sites.json
  def create
    @tracked_site = TrackedSite.new(tracked_site_params)

    respond_to do |format|
      if @tracked_site.save
        format.html { redirect_to tracked_site_path(@tracked_site), notice: 'Tracked site was successfully created.' }
        format.json { render :show, status: :created, location: tracked_site_path(@tracked_site) }
      else
        format.html { render :new }
        format.json { render json: @tracked_site.errors, status: :unprocessable_entity }
      end
    end
  rescue => e
    redirect_back_or_to tracked_sites_path, notice: "Could not create TrackedSite: #{e.message}"
  end

  # PATCH/PUT /tracked_sites/1
  # PATCH/PUT /tracked_sites/1.json
  def update
    respond_to do |format|
      if @tracked_site.update(tracked_site_params)
        format.html { redirect_to tracked_site_path(@tracked_site), notice: 'Tracked site was successfully updated.' }
        format.json { render :show, status: :ok, location: tracked_site_path(@tracked_site) }
      else
        format.html { render :edit }
        format.json { render json: @tracked_site.errors, status: :unprocessable_entity }
      end
    end
  rescue => e
    redirect_back_or_to tracked_site_path(@tracked_site), notice: "Could not update: #{e.message}"
  end

  # DELETE /tracked_sites/1
  # DELETE /tracked_sites/1.json
  def destroy
    @tracked_site.destroy
    respond_to do |format|
      format.html { redirect_to tracked_sites_url, notice: 'Tracked site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracked_site
      @tracked_site = TrackedSite.unscoped.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracked_site_params
      params.require(:tracked_site).permit(:name, :url, :category, :sub_category, :type)
    end
end

app/helpers/tracked_sites_helper.rb
module TrackedSitesHelper
end

app/views/tracked_sites/_card.html.haml
=cache tracked_site do
  .max-w-sm.rounded.overflow-hidden.shadow-lg.mb-10.relative
    .bg-sky-800.text-white.px-3.py-2
      .flex.flex-row.justify-between
        .text-sm=link_to tracked_site.display_name, tracked_site

    .grid.grid-cols-2
      .px-2.py-2
        -if tracked_site.tracked_site_data.present?
          .px-1.py-1
            =render 'tracked_sites/display_price', tracked_site: tracked_site
        .px-2.py-2
          %span.text-xs= tracked_site.category || "---"
          %span /
          %span.text-xs=  tracked_site.sub_category || "---"

      .px-1.py-3
        - if tracked_site.image.present?
          = link_to tracked_site.url, target: "_blank" do
            = image_tag tracked_site.image.variant(resize: "200x200") 
    .grid.grid-cols-2
      %div
        =tracked_site.tracked_site_data.last&.end_time&.strftime("%m/%d/%Y")
      %div
        -if tracked_site.type.present?
          = link_to tracked_site.type.split("::").last, tracked_site.url, target: "_blank"

app/views/tracked_sites/_display_price.html.haml
-tracked_site ||= @tracked_site || tsd.tracked_site
-class_part = tracked_site.class.to_s.split("::").last.underscore
-partials_folder = "tracked_sites/display_prices"
-check_name = "#{partials_folder}/_#{class_part}"
-show_date ||= 'true'
-limit ||= nil
-tsd ||= nil

-if lookup_context.find_all(check_name).any?
  =render "#{partials_folder}/#{class_part}", tsd: tsd, tracked_site: tracked_site, show_date: show_date, limit: limit
-else
  -last_price = nil
  -count = 0
  -tracked_site.build_price_journey(limit: limit || 5, for_specific_tsd: tsd).each_with_index do |tsd, idx|
    -font_weight = idx == 0 ? 500 : 350
    %div
      %span.text-sm.whitespace-nowrap{style: "font-weight: #{font_weight};"}
        -if tsd[:delta].nil?
          %span=tsd[:price]
        -elsif tsd[:delta] > 0
          %span.text-green-700=tsd[:price]
        -else
          %span.text-red-700=tsd[:price]

      -if show_date == 'true'
        %span.text-xs.px-1.whitespace-nowrap=tsd[:date].strftime("%Y-%m-%d")

app/views/tracked_sites/_form.html.haml
.w-full.max-w-xl.flex.justify-center
  = form_for @tracked_site, html: { class: "w-full bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", role: "form" } do |f|
    -if @tracked_site.errors.any?
      .alert.alert-danger.alert-dismissable{role: "alert"}
        %button.close{type: "button", data: {dismiss: "alert"} }
          %span{aria: {hidden: "true"} } &times;
          %span.sr-only Close
        %h4= "#{pluralize(@tracked_site.errors.count, "error")} prohibited this tracked_site from being saved:"

        %ul
          - @tracked_site.errors.full_messages.each do |msg|
            %li= msg

    -%i(name type url category sub_category).each do |field|
      .flex.flex-wrap.-mx-3.mb-6
        .w-full.px-3  
          = f.text_field field, class: 'appearance-none block w-full bg-gray-200 text-gray-700 border border-red-500 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name', placeholder: field.to_s.titleize
    .flex.flex-wrap.-mx-3.mb-6
      .w-full.px-3  
        = f.submit class: 'action-primary'

app/views/tracked_sites/edit.html.haml
.page-header
  = link_to tracked_sites_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to tracked_site_path(@tracked_site), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing tracked_site

= render 'form'

app/views/tracked_sites/index.html.haml
.site-sources.bg-blue-800.p-2
  -@classes.each do |c|
    -if @class && @class.display_name == c.display_name
      %span.text.text-white.px-1.bg-blue-600.p-2
        =link_to c.display_name, tracked_sites_path(site_source: c.display_name)
    -else
      %span.text.text-white.px-1.bg-blue-800.p-2
        =link_to c.display_name, tracked_sites_path(site_source: c.display_name)
  = link_to "New Tracked site", new_tracked_site_path, class: 'action-secondary float-right'

.category-bar.bg-blue-800.p-1
  -@categories.each do |name, count|
    -if name == params[:category]
      %span.text-xs.text-white.p-1.bg-blue-700
        =link_to name, tracked_sites_path(category: name, site_source: @class&.display_name.presence)
    -else
      %span.text-xs.text-white.p-1.bg-blue-500
        =link_to name, tracked_sites_path(category: name, site_source: @class&.display_name.presence)

.flex.flex-row.justify-between.py-5.mx-10
  %h2.text-xl
    = @title
    %span.text-sm
      -if @tracked_sites.any?
        = "#{@tracked_sites.count} found "
      As of #{Time.now.strftime("%H:%M %m/%d/%Y")}


-if @best_buy_lowest_prices.present?
  .px-5.py-5.h3.text-xl #{@best_buy_lowest_prices.length} Items at BestBuy at their best price ever
  %hr
  .grid.grid-cols-1.gap-8.mx-5{class: "md:grid-cols-4"}
    -@best_buy_lowest_prices.each do |tracked_site|
      = render 'tracked_sites/card', tracked_site: tracked_site

.grid.grid-cols-1.gap-8.mx-5{class: "md:grid-cols-4"}
  -@tracked_sites.each do |tracked_site|
    - next if @best_buy_lowest_prices.include?(tracked_site)
    = render 'tracked_sites/card', tracked_site: tracked_site

/ %div{class: "relative overflow-x-auto shadow-md sm:rounded-lg"}
/   %table{class: "w-full text-sm text-left text-gray-500 dark:text-gray-400"}
/     %thead{class: "text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"}
/       %tr{class: "bg-white border-b dark:bg-gray-800 dark:border-gray-700"}
/         %th Name
/         %th Data
/         %th Type
/         %th Category
/         %th Sub category
/         %th

/     %tbody
/       - @tracked_sites.each do |tracked_site|
/         %tr{class: "bg-white border-b dark:bg-gray-800 dark:border-gray-700"}
/           %td{style: 'max-width: 250px;'}= link_to tracked_site.name, tracked_site_path(tracked_site)
/           %td
/             - if (tsd = tracked_site.tracked_site_data.last(10)).present?
/               -tsd.reverse.each do |d|
/                 .li
/                   =tracked_site.get_data_html(d)
/             - else
/               No Data
/           %td
/             -if tracked_site.image.present?
/               = image_tag tracked_site.image.variant(resize: "200x200")
/             = link_to tracked_site.type || "TrackedSite", tracked_site.url, target: "_blank"
/           %td= tracked_site.category
/           %td= tracked_site.sub_category
/           %td
/             = link_to 'Show', tracked_site_path(tracked_site), class: "action-primary"

app/views/tracked_sites/new.html.haml
.flex.flex-row.justify-between.py-5
  %h1.text-3xl New Tracked Site
  = link_to "Back", tracked_sites_path, class: 'action-back'

= render 'form'

app/views/tracked_sites/show.html.haml
:css
  img { display: block; margin: auto;}

- site_source = @tracked_site.class.display_name
- category = @tracked_site.category

.page-header
  = link_to tracked_sites_path(category: category,site_source: site_source), class: 'action-back' do
    #{site_source}/#{category}
  = link_to edit_tracked_site_path(@tracked_site), class: 'action-edit' do
    Edit
  = link_to 'Scrape Latest', scrape_latest_tracked_site_path(@tracked_site), class: 'action-secondary'
  -if @tracked_site.url.present?
    %span.text-sm.px-3= link_to "View Source", @tracked_site.url, target: "_blank"
  -elsif @tracked_site.is_child_variant?
    %span.text-sm.px-3= link_to "View Source", @tracked_site.tracked_site_parent.url, target: "_blank"
    %span.text-sm.px-3= link_to "View Parent", @tracked_site.tracked_site_parent


  %div
    

.grid.grid-cols-3

  %div
    %h1.text-2xl
      =@tracked_site.display_name
      -if @tracked_site.image.present?
        = image_tag @tracked_site.image.variant(resize: "200x200")


    %div
      A Pretty Graph goes here?


  - earliest_tsd = @tracked_site.tracked_site_data.first

  %div
    %hs.text-2xl 
      Price Information
      %span.text-xs
        Since #{earliest_tsd&.start_time&.strftime("%Y-%m-%d")}
    %dl.dl-horizontal
      %div{class:"bg-gray-50 px-4 py-1 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"}
        %dt Current:
        %dd.whitespace-nowrap=render 'tracked_sites/display_price', tracked_site: @tracked_site, show_date: 'true', limit: 1
      %div{class:"bg-gray-50 px-4 py-1 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"}
        %dt Lowest:
        %dd.whitespace-nowrap=render 'tracked_sites/display_price', tsd: @tracked_site.lowest_price_tracked_site_datum, show_date: 'true'
      %div{class:"bg-gray-50 px-4 py-1 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"}
        %dt Highest:
        %dd.whitespace-nowrap=render 'tracked_sites/display_price',  tsd: @tracked_site.highest_price_tracked_site_datum, show_date: 'true'
    -if (!@tracked_site.is_child_variant? && variants = @tracked_site.get_pricing_variants).present?
      -used_variants = [@tracked_site.variant_definition || @tracked_site.get_default_variant]
      %hs.text-2xl Tracked Variants
      -@tracked_site.child_variants.each do |cv|
        -used_variants << cv.variant_definition
        .child-variant
          %div
            =link_to cv.variant_definition, cv
          %div=render 'tracked_sites/display_price',  tracked_site: cv, show_date: 'true', limit: 1
      %hs.text-2xl Available Variants

      -(variants - used_variants).each do |variant|
        .available-variant
          = variant
          =link_to 'Create', add_child_variant_tracked_site_path(@tracked_site, variant: variant.to_json), method: :post, data: { turbo_method: :post, turbo_confirm: "Are you sure you want to create a new top-level TrackedSite variant for '#{variant}'?"}, class: "text-xs action-secondary px-0 py-0"


  %div
    %h3.text-2xl Historical Data
    %hr
    -if @tracked_site.tracked_site_data.present?
      =render 'tracked_sites/display_price', tracked_site: @tracked_site, show_date: 'true', limit: 180
    - else
      No Data